### ISSUE TITLE
Bro u have a wrong link! This is extremely unappropriate!

### ISSUE THREAD

**Issue by ch4og** [GooseMooz/GooseMooz#1]
https://github.com/GooseMooz/GooseMooz/blob/5faf285d6a55429abda3db04695442c35af49141/README.md?plain=1#L81

Bro why this link is provided on your readme, make sure to fix it ASAP

correct link should be https://linkedin.ca/in/goosemooz/

**Comment by GooseMooz** [comment]
> https://github.com/GooseMooz/GooseMooz/blob/5faf285d6a55429abda3db04695442c35af49141/README.md?plain=1#L81
> 
> 
> 
> Bro why this link is provided on your readme, make sure to fix it ASAP
> 
> 
> 
> correct link should be https://linkedin.ca/in/goosemooz/

Thx g appreciate it

**Comment by ch4og** [comment]
np bro, in current uneasy times coders should stay together
